### ISSUE TITLE
Problem mounting under Docker

### ISSUE THREAD

**Issue by briantopping** [thecodeteam/csi-nfs#10]
@clintkitson was kind enough to toss in on https://github.com/thecodeteam/rexray/issues/1114 and once it was clear how to specify options, a lot more made sense.

That said, I think there may be a compatibility issue with the plugin as I built up in https://github.com/thecodeteam/rexray/issues/1114#issuecomment-345550823 over several comments. The mount is happening, but at a directory name that includes a `:`. Docker seems to be parsing that and dropping the colon and everything after it as it tries to map the external volume.

**Comment by briantopping** [comment]
By the way, I'm really thrilled for the work everyone is doing on this project and if there's anything I can do to facilitate here, it would be my pleasure to help out. Apologies in advance if this is PBKAC. If not, I'm really looking forward to learning from the PRs that come from it.

**Comment by clintkitson** [comment]
Thanks for filing this @briantopping. Asking more questions in the RR channel.

**Comment by briantopping** [comment]
I don't understand fully why this was an issue, some misuse of the overall system no doubt. I can't reproduce it at this point, closing.
